### ISSUE TITLE
TS definitions

### ISSUE THREAD

**Issue by MichalBryxi** [html-next/ember-raf-scheduler#7]
👋  would be nice to add TS definitions. When trying to use it in our `*.ts` code I'm. getting:

```
Cannot find module 'ember-raf-scheduler/test-support/register-waiter' or its corresponding type declarations.
```

**Comment by mixonic** [comment]
@MichalBryxi I'd be happy to have them as well, or to have this library written in TS. I'm not even sure this library should exist outside of vertical collection, however.

Regardless, there are lots of things we want, and I'm not sure if this is super actionable as an issue. I'm going to close it as we've discussed the topic. Feel free to re-open if I'm missing anything!

**Comment by MichalBryxi** [comment]
Sorry @mixonic this was supposed to be accompanied by a PR and then I got derailed by [waves in general direction] life. I'm not sure whether this is still a thing in our codebase, but if it is I would be happy to provide the TS definitions if it makes sense.
